# Generated by Django 2.0.2 on 2018-04-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_description', models.CharField(max_length=200)),
                ('is_public', models.BooleanField(default=False)),
                ('is_created', models.BooleanField(default=False)),
            ],
        ),
    ]
