# Generated by Django 2.0.2 on 2018-05-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datenight_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_url',
            field=models.ImageField(upload_to=''),
        ),
    ]
