# Generated by Django 2.0.2 on 2018-04-17 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datenight_backend', '0004_comment_destinationnode_image_node_travelnode'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datenight_backend.Image'),
        ),
    ]
