# Generated by Django 2.0.2 on 2018-05-05 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datenight_backend', '0004_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationnode',
            name='destination_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datenight_backend.Address'),
        ),
        migrations.AddField(
            model_name='travelnode',
            name='destination_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end', to='datenight_backend.Address'),
        ),
        migrations.AddField(
            model_name='travelnode',
            name='starting_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start', to='datenight_backend.Address'),
        ),
    ]
