# Generated by Django 2.0.2 on 2018-04-17 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datenight_backend', '0006_image_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datenight_backend.Date'),
        ),
    ]
