# Generated by Django 2.0.2 on 2018-04-17 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datenight_backend', '0009_auto_20180417_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelnode',
            name='node',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='datenight_backend.Node'),
        ),
    ]
