# Generated by Django 2.0.2 on 2018-04-25 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datenight_backend', '0010_travelnode_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datenight_backend.Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
