# Generated by Django 2.0.2 on 2018-04-25 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datenight_backend', '0011_featureddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datenight_backend.Date')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datenight_backend.Tag')),
            ],
        ),
    ]
