# Generated by Django 2.0.2 on 2018-04-25 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datenight_backend', '0014_userdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datenight_backend.Node')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
